const path = require('path');

module.exports = {
	title: 'JSECoin Platform Guide',
	//defaultExample: true,
	components: './src/components/**/*.vue',
	usageMode: 'expand',//showUsage: true,
	exampleMode: 'expand',//showCode: true,
	showSidebar: true,
	styleguideDir: './dist_styleguide',
	//navigation: true,
	//vuex: './src/store/index',
	renderRootJsx: path.join(__dirname, 'public/docs/styleguide.root.js'),
	ribbon: {
		url: 'https://github.com/jsecoin',
		text: 'JSECoin on GitHub',
	},
	styleguideComponents: {
		'@': path.join(__dirname, './src'),
	},
	//load in additional required images
	require: [
		path.join(__dirname, 'public/docs/global.requires.js'),
		path.join(__dirname, 'public/docs/css/styles.css'),
		path.join(__dirname, 'public/static/styleguide/dashboard-overview.png'),
		path.join(__dirname, 'public/static/styleguide/dashboard-account.png'),
		path.join(__dirname, 'public/static/styleguide/mine-earnings.png'),
		path.join(__dirname, 'public/static/styleguide/mine-platform.png'),
		path.join(__dirname, 'public/static/styleguide/settings.png'),
		path.join(__dirname, 'public/static/styleguide/wallet-export.png'),
		path.join(__dirname, 'public/static/styleguide/wallet-import.png'),
		path.join(__dirname, 'public/static/styleguide/wallet-transactions.png'),
		path.join(__dirname, 'public/static/styleguide/wallet-transfer.png'),
		path.join(__dirname, 'public/static/styleguide/login.png'),
	],
	sections: [
		{
			name: 'Project Overview',
			content: './public/docs/Getting-Started.md',
		},
		{
			name: 'Pages',
			content: './public/docs/Pages.md',
			components: () => [
				'./src/views/SplashLoadingScreen-Page.vue',
				'./src/views/UpgradeApp-Page.vue',
				'./src/views/Login-Page.vue',
				'./src/views/dashboard/Overview-Page.vue',
				'./src/views/dashboard/Account-Page.vue',
				'./src/views/wallet/Export-Page.vue',
				'./src/views/wallet/Import-Page.vue',
				'./src/views/wallet/Transfer-Page.vue',
				'./src/views/wallet/WalletTransactions-Page.vue',
				'./src/views/mine/PlatformMiner-Page.vue',
				'./src/views/mine/Earnings-Page.vue',
				'./src/views/settings/Settings-Page.vue',
			],
		},
		{
			name: 'Widgets',
			content: './public/docs/Widgets.md',
			components: () => [
				'./src/components/widgets/AppWrapperWidget.vue',
				'./src/components/widgets/ButtonWidget.vue',
				'./src/components/widgets/Coin.vue',
				//'./src/components/widgets/ChartWidget.vue', replaced with c3 chart...
				'./src/components/widgets/CoinCodeWidget.vue',
				'./src/components/widgets/CoinStatusWidget.vue',
				'./src/components/widgets/ConsoleWidget.vue',
				'./src/components/widgets/ContentWidget.vue',
				'./src/components/widgets/FormErrorDisplayWidget.vue',
				'./src/components/widgets/GenerateBookletWidget.vue',
				'./src/components/widgets/InputWidget.vue',
				'./src/components/widgets/LoadingDelayMaskWidget.vue',
				'./src/components/widgets/MiningAcceleratorWidget.vue',
				'./src/components/widgets/MiningChartWidget.vue',
				'./src/components/widgets/MiningOverviewPanelWidget.vue',
				'./src/components/widgets/NavWidget.vue',
				'./src/components/widgets/OptionsListWrapperWidget.vue',
				'./src/components/widgets/OverviewCoinDispayWidget.vue',
				'./src/components/widgets/QRCoinCodeWidget.vue',
				'./src/components/widgets/ScrollWidget.vue',
				'./src/components/widgets/SettingsItemRowWidget.vue',
				'./src/components/widgets/SpinnerWidget.vue',
				'./src/components/widgets/Splash.vue',
				'./src/components/widgets/ToggleSwitchWidget.vue',
				'./src/components/widgets/TwoFA.vue',
			],
		},
	],
};
